package network.bisq.mobile.client.offerbook.market
val DEFAULT_MARKETS = """
       [
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"USD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"US Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"EUR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Euro"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"GBP","baseCurrencyName":"Bitcoin","quoteCurrencyName":"British Pound"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"CAD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Canadian Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"AUD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Australian Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"RUB","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Russian Ruble"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"CNY","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Chinese Yuan"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"INR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Indian Rupee"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"NGN","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Nigerian Naira"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"BHD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Bahraini Dinar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"BDT","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Bangladeshi Taka"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"BMD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Bermudan Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"BRL","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Brazilian Real"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"CLP","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Chilean Peso"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"CZK","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Czech Koruna"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"DKK","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Danish Krone"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"GEL","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Georgian Lari"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"HKD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Hong Kong Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"HUF","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Hungarian Forint"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"IDR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Indonesian Rupiah"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"ILS","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Israeli New Shekel"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"JPY","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Japanese Yen"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"KWD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Kuwaiti Dinar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"MYR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Malaysian Ringgit"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"MXN","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Mexican Peso"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"MMK","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Myanmar Kyat"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"TWD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"New Taiwan Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"NZD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"New Zealand Dollar"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"NOK","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Norwegian Krone"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"PKR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Pakistani Rupee"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"PHP","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Philippine Peso"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"PLN","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Polish Zloty"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"SAR","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Saudi Riyal"},
            {"baseCurrencyCode":"BTC","quoteCurrencyCode":"SGD","baseCurrencyName":"Bitcoin","quoteCurrencyName":"Singapore Dollar"}
        ]
    """.trimIndent()