package network.bisq.mobile.domain

// Currency names are from english locale. In Bisq2 we use the users language locale for getting the names.
val fiatNameByCode = mapOf(
    Pair("USD", "US Dollar"),
    Pair("EUR", "Euro"),
    Pair("GBP", "British Pound"),
    Pair("CAD", "Canadian Dollar"),
    Pair("AUD", "Australian Dollar"),
    Pair("RUB", "Russian Ruble"),
    Pair("CNY", "Chinese Yuan"),
    Pair("INR", "Indian Rupee"),
    Pair("NGN", "Nigerian Naira"),
    Pair("AFN", "Afghan Afghani"),
    Pair("ALL", "Albanian Lek"),
    Pair("DZD", "Algerian Dinar"),
    Pair("AOA", "Angolan Kwanza"),
    Pair("ARS", "Argentine Peso"),
    Pair("AMD", "Armenian Dram"),
    Pair("AWG", "Aruban Florin"),
    Pair("AZN", "Azerbaijani Manat"),
    Pair("BSD", "Bahamian Dollar"),
    Pair("BHD", "Bahraini Dinar"),
    Pair("BDT", "Bangladeshi Taka"),
    Pair("BBD", "Barbadian Dollar"),
    Pair("BYN", "Belarusian Ruble"),
    Pair("BZD", "Belize Dollar"),
    Pair("BMD", "Bermudan Dollar"),
    Pair("BTN", "Bhutanese Ngultrum"),
    Pair("BOB", "Bolivian Boliviano"),
    Pair("BAM", "Bosnia-Herzegovina Convertible Mark"),
    Pair("BWP", "Botswanan Pula"),
    Pair("BRL", "Brazilian Real"),
    Pair("BND", "Brunei Dollar"),
    Pair("BGN", "Bulgarian Lev"),
    Pair("BIF", "Burundian Franc"),
    Pair("XPF", "CFP Franc"),
    Pair("KHR", "Cambodian Riel"),
    Pair("CVE", "Cape Verdean Escudo"),
    Pair("KYD", "Cayman Islands Dollar"),
    Pair("XAF", "Central African CFA Franc"),
    Pair("CLP", "Chilean Peso"),
    Pair("COP", "Colombian Peso"),
    Pair("KMF", "Comorian Franc"),
    Pair("CDF", "Congolese Franc"),
    Pair("CRC", "Costa Rican Colón"),
    Pair("CUP", "Cuban Peso"),
    Pair("CZK", "Czech Koruna"),
    Pair("DKK", "Danish Krone"),
    Pair("DJF", "Djiboutian Franc"),
    Pair("DOP", "Dominican Peso"),
    Pair("XCD", "East Caribbean Dollar"),
    Pair("EGP", "Egyptian Pound"),
    Pair("ERN", "Eritrean Nakfa"),
    Pair("ETB", "Ethiopian Birr"),
    Pair("FKP", "Falkland Islands Pound"),
    Pair("FJD", "Fijian Dollar"),
    Pair("GMD", "Gambian Dalasi"),
    Pair("GEL", "Georgian Lari"),
    Pair("GHS", "Ghanaian Cedi"),
    Pair("GIP", "Gibraltar Pound"),
    Pair("GTQ", "Guatemalan Quetzal"),
    Pair("GNF", "Guinean Franc"),
    Pair("GYD", "Guyanaese Dollar"),
    Pair("HTG", "Haitian Gourde"),
    Pair("HNL", "Honduran Lempira"),
    Pair("HKD", "Hong Kong Dollar"),
    Pair("HUF", "Hungarian Forint"),
    Pair("ISK", "Icelandic Króna"),
    Pair("IDR", "Indonesian Rupiah"),
    Pair("IRR", "Iranian Rial"),
    Pair("IQD", "Iraqi Dinar"),
    Pair("ILS", "Israeli New Shekel"),
    Pair("JMD", "Jamaican Dollar"),
    Pair("JPY", "Japanese Yen"),
    Pair("JOD", "Jordanian Dinar"),
    Pair("KZT", "Kazakhstani Tenge"),
    Pair("KES", "Kenyan Shilling"),
    Pair("KWD", "Kuwaiti Dinar"),
    Pair("KGS", "Kyrgystani Som"),
    Pair("LAK", "Laotian Kip"),
    Pair("LBP", "Lebanese Pound"),
    Pair("LSL", "Lesotho Loti"),
    Pair("LRD", "Liberian Dollar"),
    Pair("LYD", "Libyan Dinar"),
    Pair("MOP", "Macanese Pataca"),
    Pair("MKD", "Macedonian Denar"),
    Pair("MGA", "Malagasy Ariary"),
    Pair("MWK", "Malawian Kwacha"),
    Pair("MYR", "Malaysian Ringgit"),
    Pair("MVR", "Maldivian Rufiyaa"),
    Pair("MRU", "Mauritanian Ouguiya"),
    Pair("MUR", "Mauritian Rupee"),
    Pair("MXN", "Mexican Peso"),
    Pair("MDL", "Moldovan Leu"),
    Pair("MNT", "Mongolian Tugrik"),
    Pair("MAD", "Moroccan Dirham"),
    Pair("MZN", "Mozambican Metical"),
    Pair("MMK", "Myanmar Kyat"),
    Pair("NAD", "Namibian Dollar"),
    Pair("NPR", "Nepalese Rupee"),
    Pair("ANG", "Netherlands Antillean Guilder"),
    Pair("TWD", "New Taiwan Dollar"),
    Pair("NZD", "New Zealand Dollar"),
    Pair("NIO", "Nicaraguan Córdoba"),
    Pair("KPW", "North Korean Won"),
    Pair("NOK", "Norwegian Krone"),
    Pair("OMR", "Omani Rial"),
    Pair("PKR", "Pakistani Rupee"),
    Pair("PAB", "Panamanian Balboa"),
    Pair("PGK", "Papua New Guinean Kina"),
    Pair("PYG", "Paraguayan Guarani"),
    Pair("PEN", "Peruvian Sol"),
    Pair("PHP", "Philippine Peso"),
    Pair("PLN", "Polish Zloty"),
    Pair("QAR", "Qatari Riyal"),
    Pair("RON", "Romanian Leu"),
    Pair("RWF", "Rwandan Franc"),
    Pair("SVC", "Salvadoran Colón"),
    Pair("WST", "Samoan Tala"),
    Pair("SAR", "Saudi Riyal"),
    Pair("RSD", "Serbian Dinar"),
    Pair("SCR", "Seychellois Rupee"),
    Pair("SLE", "Sierra Leonean Leone"),
    Pair("SGD", "Singapore Dollar"),
    Pair("SBD", "Solomon Islands Dollar"),
    Pair("SOS", "Somali Shilling"),
    Pair("ZAR", "South African Rand"),
    Pair("KRW", "South Korean Won"),
    Pair("SSP", "South Sudanese Pound"),
    Pair("LKR", "Sri Lankan Rupee"),
    Pair("SHP", "St. Helena Pound"),
    Pair("SDG", "Sudanese Pound"),
    Pair("SRD", "Surinamese Dollar"),
    Pair("SZL", "Swazi Lilangeni"),
    Pair("SEK", "Swedish Krona"),
    Pair("CHF", "Swiss Franc"),
    Pair("SYP", "Syrian Pound"),
    Pair("STN", "São Tomé & Príncipe Dobra"),
    Pair("TJS", "Tajikistani Somoni"),
    Pair("TZS", "Tanzanian Shilling"),
    Pair("THB", "Thai Baht"),
    Pair("TOP", "Tongan Paʻanga"),
    Pair("TTD", "Trinidad & Tobago Dollar"),
    Pair("TND", "Tunisian Dinar"),
    Pair("TRY", "Turkish Lira"),
    Pair("TMT", "Turkmenistani Manat"),
    Pair("UGX", "Ugandan Shilling"),
    Pair("UAH", "Ukrainian Hryvnia"),
    Pair("AED", "United Arab Emirates Dirham"),
    Pair("UYU", "Uruguayan Peso"),
    Pair("UZS", "Uzbekistani Som"),
    Pair("VUV", "Vanuatu Vatu"),
    Pair("VES", "Venezuelan Bolívar"),
    Pair("VND", "Vietnamese Dong"),
    Pair("XOF", "West African CFA Franc"),
    Pair("YER", "Yemeni Rial"),
    Pair("ZMW", "Zambian Kwacha"),
    Pair("ZWL", "Zimbabwean Dollar (2009)"),
)