package network.bisq.mobile.presentation.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class BisqColors (
    val dark1: Color,
    val dark2: Color,
    val dark3: Color,
    val dark4: Color,
    val dark5: Color,
    val light1: Color,
    val light2: Color,
    val light3: Color,
    val light4: Color,
    val light5: Color,
    val grey1: Color,
    val grey2: Color,
    val grey3: Color,
    val grey4: Color,
    val grey5: Color,
    val primary: Color,
    val primaryHover: Color,
    val primaryDisabled: Color,
    val primary2: Color,
    val secondary: Color,
    val secondaryHover: Color,
    val secondaryDisabled: Color,
    val danger: Color,
    val dangerHover: Color,
    val dangerDisabled: Color,
    val warning: Color,
    val warningHover: Color,
    val warningDisabled: Color,
    val backgroundColor: Color,
)


val LocalBisqColors = staticCompositionLocalOf {
    BisqColors(
        dark1 = Color.Unspecified,
        dark2 = Color.Unspecified,
        dark3 = Color.Unspecified,
        dark4 = Color.Unspecified,
        dark5 = Color.Unspecified,
        light1 = Color.Unspecified,
        light2 = Color.Unspecified,
        light3 = Color.Unspecified,
        light4 = Color.Unspecified,
        light5 = Color.Unspecified,
        grey1 = Color.Unspecified,
        grey2 = Color.Unspecified,
        grey3 = Color.Unspecified,
        grey4 = Color.Unspecified,
        grey5 = Color.Unspecified,
        primary = Color.Unspecified,
        primaryHover = Color.Unspecified,
        primaryDisabled = Color.Unspecified,
        primary2 = Color.Unspecified,
        secondary = Color.Unspecified,
        secondaryHover = Color.Unspecified,
        secondaryDisabled = Color.Unspecified,
        danger = Color.Unspecified,
        dangerHover = Color.Unspecified,
        dangerDisabled = Color.Unspecified,
        warning = Color.Unspecified,
        warningHover = Color.Unspecified,
        warningDisabled = Color.Unspecified,
        backgroundColor = Color.Unspecified,
    )
}

val lightColors = BisqColors(
    dark1 = Color(0xFFFFFFFF),
    dark2 = Color(0xFFF8F8F8),
    dark3 = Color(0xFFF4F4F4),
    dark4 = Color(0xFFF0F0F0),
    dark5 = Color(0xFFEFEFEF),
    light1 = Color(0xFF1D1D1D),
    light2 = Color(0xFF212121),
    light3 = Color(0xFF262626),
    light4 = Color(0xFF282828),
    light5 = Color(0xFF333333),
    grey1 = Color(0xFF999999),
    grey2 = Color(0xFF747474),
    grey3 = Color(0xFF6B6B6B),
    grey4 = Color(0xFF515151),
    grey5 = Color(0xFF4F4F4F),
    primary = Color(0xFF25B135),
    primaryHover = Color(0xFF56C262),
    primaryDisabled = Color(0x6625B135),
    primary2 = Color(0xFF0A2F0F),
    secondary = Color(0xFF2F2F2F),
    secondaryHover = Color(0xFF525252),
    secondaryDisabled = Color(0x662F2F2F),
    danger = Color(0xFFDB0000),
    dangerHover = Color(0xFFAC2B2B),
    dangerDisabled = Color(0x66DB0000),
    warning = Color(0xFFFF9823),
    warningHover = Color(0xFFFFAC4E),
    warningDisabled = Color(0xB3FF9823),
    backgroundColor = Color(0xFF1C1C1C),
)

val darkColors = BisqColors(
    dark1 = Color(0xFF1D1D1D),
    dark2 = Color(0xFF212121),
    dark3 = Color(0xFF262626),
    dark4 = Color(0xFF282828),
    dark5 = Color(0xFF333333),
    light1 = Color(0xFFFFFFFF),
    light2 = Color(0xFFF8F8F8),
    light3 = Color(0xFFF4F4F4),
    light4 = Color(0xFFF0F0F0),
    light5 = Color(0xFFEFEFEF),
    grey1 = Color(0xFF999999),
    grey2 = Color(0xFF747474),
    grey3 = Color(0xFF6B6B6B),
    grey4 = Color(0xFF515151),
    grey5 = Color(0xFF4F4F4F),
    primary = Color(0xFF25B135),
    primaryHover = Color(0xFF56C262),
    primaryDisabled = Color(0x6625B135),
    primary2 = Color(0xFF0A2F0F),
    secondary = Color(0xFF2F2F2F),
    secondaryHover = Color(0xFF525252),
    secondaryDisabled = Color(0x662F2F2F),
    danger = Color(0xFFDB0000),
    dangerHover = Color(0xFFAC2B2B),
    dangerDisabled = Color(0x66DB0000),
    warning = Color(0xFFFF9823),
    warningHover = Color(0xFFFFAC4E),
    warningDisabled = Color(0xB3FF9823),
    backgroundColor = Color(0xFF1C1C1C),
)
