import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.cocoapods)
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.compose)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    // Sentry-KMP gradle plugin — auto-installs the Sentry Cocoa pod with the
    // correct cinterop config for the iOS target. Replaces a hand-written
    // `pod("Sentry")` block which was crashing cinterop with
    // `SentryMechanismMeta declared twice`. See [[project_analytics_phase0_plan]].
    alias(libs.plugins.sentry.kotlin.multiplatform)
    alias(libs.plugins.kover)
    // google-services plugin is applied conditionally below when
    // google-services.json is present (gitignored — provisioned per
    // environment: prod LLC project for releases, dev project for end-to-end
    // testing, stub generated by ci.yml for CI). Without it, the FCM library
    // is bundled but inert and push notification opt-in surfaces as a config
    // error at runtime.
}

if (file("google-services.json").exists()) {
    apply(
        plugin =
            libs.plugins.google.services
                .get()
                .pluginId,
    )
    logger.lifecycle("FCM enabled — applying google-services plugin")
} else {
    logger.lifecycle(
        "FCM disabled — apps/clientApp/google-services.json not found. " +
            "Push notifications will fail at runtime; this is fine for local " +
            "dev and CI builds without the GOOGLE_SERVICES_JSON_BASE64 secret.",
    )
}

// -------------------- Version Configuration --------------------
version = project.findProperty("client.android.version") as String
val versionCodeValue = (project.findProperty("client.android.version.code") as String).toInt()
val sharedVersion = project.findProperty("shared.version") as String
val appName = project.findProperty("client.name") as String
val iosVersion = project.findProperty("client.ios.version") as String

// -------------------- Module References --------------------
val clientFrameworkBaseName = "ClientApp"
val sharedPresentationModule = ":shared:presentation"
val sharedDomainModule = ":shared:domain"
val sharedKScanModule = ":shared:kscan"
val sharedTestUtilsModule = ":shared:test-utils"

dependencies {
    debugImplementation(libs.compose.ui.tooling)
    // IMPORTANT: This is needed for Robolectric tests to work in both variants
    // The fact that its needed to be included in the build might be a compose issue
    // We accept that for now as the lib size is minimal and won't impact the prod code.
    implementation(libs.androidx.test.compose.manifest)
}

// -------------------- Kotlin Multiplatform Configuration --------------------
kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    fun org.jetbrains.kotlin.gradle.plugin.mpp.Framework.configureSharedExports() {
        export(project(sharedPresentationModule))
        export(project(sharedDomainModule))
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = clientFrameworkBaseName
            configureSharedExports()

            // The Sentry cinterop manifest contributes `-framework Sentry`,
            // but the standalone Kotlin/Native framework linker does not
            // inherit CocoaPods' FRAMEWORK_SEARCH_PATHS from the synthetic
            // Pods xcconfig. Xcode supplies that path itself, which is why
            // the IDE build can succeed while `:clientApp:build` fails with
            // `ld: framework 'Sentry' not found`.
            val appleSdkName =
                if (iosTarget.name == "iosArm64") {
                    "iphoneos"
                } else {
                    "iphonesimulator"
                }
            // Always Debug-<sdk>: the cocoapods plugin builds each pod once per SDK, in Debug
            // configuration only — there is no Release-<sdk> pod output, and the Debug-built
            // Sentry is fine for RELEASE framework links too (the -F path only serves symbol
            // resolution; the framework actually embedded into the app is Xcode's own build).
            val sentryFrameworkSearchPath =
                layout.buildDirectory
                    .dir("cocoapods/synthetic/ios/build/Debug-$appleSdkName/Sentry")
                    .get()
                    .asFile
                    .absolutePath
            linkerOpts("-F$sentryFrameworkSearchPath")

            // Link Swift bridge object files (only from domain module to avoid duplicates).
            // Per-SDK dir: device and simulator objects are not interchangeable.
            val swiftBridgeModules = listOf("LocalEncryptionBridge", "PushNotificationKeyStore")
            val domainSwiftBridgeDir =
                project(":shared:domain")
                    .layout.buildDirectory
                    .dir("swift-bridge/$appleSdkName")
                    .get()
                    .asFile

            val objectFiles =
                swiftBridgeModules.map { moduleName ->
                    File(domainSwiftBridgeDir, "$moduleName.o").absolutePath
                }

            val isMac = System.getProperty("os.name").lowercase().contains("mac")
            if (isMac) {
                try {
                    // Same DEVELOPER_DIR resolution as the shared modules' getSwiftLibPath.
                    val developerPath =
                        System.getenv("DEVELOPER_DIR")
                            ?: "/Applications/Xcode.app/Contents/Developer"
                    val swiftLibPath = "$developerPath/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$appleSdkName"
                    linkerOpts(
                        *objectFiles.toTypedArray(),
                        "-L$swiftLibPath",
                        "-lswiftCore",
                        "-lswiftFoundation",
                        "-lswiftDispatch",
                        "-lswiftObjectiveC",
                        "-lswiftDarwin",
                        "-lswiftCoreFoundation",
                    )
                } catch (e: Exception) {
                    project.logger.warn("Could not configure Swift library path: ${e.message}")
                }
            }
        }
    }

    cocoapods {
        summary = "Bisq Connect Application"
        homepage = "X"
        version = iosVersion
        ios.deploymentTarget = "16.0"
        podfile = project.file("../../iosClient/Podfile")
        framework {
            baseName = clientFrameworkBaseName
            isStatic = true
            configureSharedExports()
        }
        // Sentry Cocoa SDK pod, coordinated by the Sentry-KMP gradle plugin
        // (applied in the plugins{} block above). The pattern mirrors
        // Sentry-KMP's own sample at tag 0.26.0:
        //   sentry-samples/kmp-app-cocoapods/shared/build.gradle.kts
        //
        // Version pinned to Sentry-KMP 0.26.0's expected Sentry Cocoa SDK
        // (sentry-kotlin-multiplatform/buildSrc/src/main/java/Config.kt →
        //  sentryCocoaVersion = "8.58.2"). When bumping
        // libs.versions.toml's sentry-kotlin-multiplatform, check that tag's
        // Config.kt for the matching Cocoa version and update both here AND
        // iosClient/Podfile.lock.
        //
        // `-fmodules` enables Objective-C module imports during cinterop —
        // required, otherwise cinterop crashes with
        //   IllegalArgumentException: 'SentryMechanismMeta' is going to be declared twice
        //
        // Sentry Cocoa is statically linked into every iOS build. Aligns with
        // the Android side now too — both platforms ship the SDK linked but
        // inert until the user-settings toggle is flipped ON. Trade-off: a
        // few hundred KB binary cost in exchange for end users getting a
        // ready-to-flip release build (no rebuild needed to enable).
        pod("Sentry") {
            version = "8.58.2"
            extraOpts += listOf("-compiler-option", "-fmodules")
        }
    }

    sourceSets {
        commonMain.dependencies {
            // Project modules
            api(project(sharedDomainModule))
            api(project(sharedKScanModule))
            api(project(sharedPresentationModule))

            // Compose
            implementation(libs.compose.components.resources)
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.material.icons.extended)

            // AndroidX
            implementation(libs.androidx.datastore.okio)

            // KotlinX
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.core)
            implementation(libs.kotlinx.serialization.json)

            // Koin
            implementation(libs.koin.compose)
            implementation(libs.koin.core)

            // Ktor
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.websockets)
            implementation(libs.ktor.network)
            implementation(libs.ktor.serialization.kotlinx.json)

            // Other libraries
            implementation(libs.atomicfu)
            implementation(libs.bignum)
            implementation(libs.logging.kermit)
            implementation(libs.navigation.compose)
        }

        commonTest.dependencies {
            // Kotlin
            implementation(libs.kotlin.test)

            // KotlinX
            implementation(libs.kotlinx.coroutines.test)

            // Koin
            implementation(libs.koin.test)

            // Test utilities
            implementation(project(sharedTestUtilsModule))
        }

        androidMain.dependencies {
            // AndroidX
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.splashscreen)
            implementation(libs.androidx.security.crypto)

            // Koin
            implementation(libs.koin.android)

            // Ktor
            implementation(libs.ktor.client.okhttp)

            // Firebase Cloud Messaging — version pinned by BoM. Note: the
            // `-ktx` artifact has been deprecated; the main `firebase-messaging`
            // module now bundles the Kotlin extensions.
            implementation(project.dependencies.platform(libs.firebase.bom))
            implementation(libs.firebase.messaging)
            implementation(libs.kotlinx.coroutines.play.services)
        }

        androidUnitTest.dependencies {
            // AndroidX
            implementation(libs.androidx.test.compose.junit4)
            implementation(libs.androidx.test.core)
            implementation(libs.androidx.test.espresso.core)
            implementation(libs.androidx.test.junit)
            implementation(libs.androidx.test.compose.manifest)

            // Kotlin
            implementation(libs.kotlin.test)
            implementation(libs.kotlin.test.junit)

            // KotlinX
            implementation(libs.kotlinx.coroutines.test)

            // Other libraries
            implementation(libs.junit)
            implementation(libs.mockk)
            implementation(libs.robolectric)

            // Test utilities
            implementation(project(sharedTestUtilsModule))
        }
    }
}

// -------------------- Local Properties --------------------
val localProperties = Properties()
localProperties.load(File(rootDir, "local.properties").inputStream())

// -------------------- Android Configuration --------------------
android {
    namespace = "network.bisq.mobile.client"
    compileSdk =
        libs.versions.android.compileSdk
            .get()
            .toInt()

    signingConfigs {
        create("release") {
            if (localProperties["KEYSTORE_PATH"] != null) {
                storeFile = file(localProperties["KEYSTORE_PATH"] as String)
                storePassword = localProperties["KEYSTORE_PASSWORD"] as String
                keyAlias = localProperties["CLI_KEY_ALIAS"] as String
                keyPassword = localProperties["CLI_KEY_PASSWORD"] as String
            }
        }
    }

    defaultConfig {
        applicationId = "network.bisq.mobile.client"
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()
        targetSdk =
            libs.versions.android.targetSdk
                .get()
                .toInt()
        versionCode = versionCodeValue
        versionName = version.toString()

        buildConfigField("String", "APP_VERSION", "\"${version}\"")
        buildConfigField("String", "SHARED_VERSION", "\"${sharedVersion}\"")
    }

    // Enable resources for Robolectric unit tests
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            // The following excludes are needed to avoid protobuf hanging build when merging release resources for java
            // Exclude the conflicting META-INF files
            excludes.add("META-INF/versions/9/OSGI-INF/MANIFEST.MF")
            excludes.add("META-INF/DEPENDENCIES")
            excludes.add("META-INF/LICENSE*.md")
            excludes.add("META-INF/NOTICE*.md")
            excludes.add("META-INF/INDEX.LIST")
            excludes.add("META-INF/NOTICE.markdown")

            pickFirsts +=
                listOf(
                    "META-INF/LICENSE*",
                    "META-INF/NOTICE*",
                    "META-INF/services/**",
                    "META-INF/*.version",
                )
        }
        jniLibs {
            // For apk release builds after tor inclusion
            // If multiple .so files exist across dependencies, pick the first and avoid conflicts
            pickFirsts +=
                listOf(
                    "lib/**/libtor.so",
                    "lib/**/libcrypto.so",
                    "lib/**/libevent*.so",
                    "lib/**/libssl.so",
                    "lib/**/libsqlite*.so",
                    "lib/**/libdatastore_shared_counter.so",
                )
            // Exclude problematic native libraries
            excludes +=
                listOf(
                    "**/libmagtsync.so",
                    "**/libMEOW*.so",
                )
            // Required for kmp-tor exec resources - helps prevent EOCD corruption
            useLegacyPackaging = true
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            dependenciesInfo {
                includeInApk = false
                includeInBundle = false
            }
            isDebuggable = false
            isCrunchPngs = true
        }

        getByName("debug") {
            isDebuggable = true
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    applicationVariants.all {
        val variant = this
        outputs.all {
            val output = this as com.android.build.gradle.internal.api.BaseVariantOutputImpl
            val version = variant.versionName
            val fileName = "${appName.replace(" ", "_")}-$version.apk"
            output.outputFileName = fileName
        }
    }

    buildFeatures {
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    // Needed for aab files renaming
    setProperty("archivesBaseName", getArtifactName(defaultConfig))
}

// -------------------- Build Tasks Configuration --------------------
// Ensure generateResourceBundles runs before Android build tasks
afterEvaluate {
    val generateResourceBundlesTask = project(sharedDomainModule).tasks.findByName("generateResourceBundles")
    if (generateResourceBundlesTask != null) {
        tasks
            .matching { task ->
                task.name.startsWith("compile") ||
                    task.name.startsWith("assemble") ||
                    task.name.startsWith("bundle") ||
                    task.name.contains("Build")
            }.configureEach {
                dependsOn(generateResourceBundlesTask)
            }
    }
}

// -------------------- iOS Version Sync Task --------------------
val iosVersionCode = project.findProperty("client.ios.version.code") as String

tasks.register("syncIosVersion") {
    group = "ios"
    description = "Syncs iOS version from gradle.properties to Config.xcconfig"

    // Capture values at configuration time for configuration cache compatibility
    val xcConfigPath =
        layout.projectDirectory
            .file("../../iosClient/Configuration/Config.xcconfig")
            .asFile.absolutePath
    val versionToSync = iosVersion
    val versionCodeToSync = iosVersionCode

    doLast {
        val xcConfigFile = File(xcConfigPath)
        if (xcConfigFile.exists()) {
            val originalContent = xcConfigFile.readText()
            var content = originalContent

            // Update APP_VERSION
            val versionRegex = Regex("APP_VERSION=.*")
            if (versionRegex.containsMatchIn(content)) {
                content = content.replace(versionRegex, "APP_VERSION=$versionToSync")
            } else {
                logger.warn("APP_VERSION key not found in Config.xcconfig — version not synced")
            }

            // Update APP_VERSION_CODE
            val versionCodeRegex = Regex("APP_VERSION_CODE=.*")
            if (versionCodeRegex.containsMatchIn(content)) {
                content = content.replace(versionCodeRegex, "APP_VERSION_CODE=$versionCodeToSync")
            } else {
                logger.warn("APP_VERSION_CODE key not found in Config.xcconfig — version code not synced")
            }

            xcConfigFile.writeText(content)
            logger.lifecycle("Updated iOS version to $versionToSync ($versionCodeToSync) in Config.xcconfig")
        } else {
            logger.warn("Config.xcconfig not found at $xcConfigPath")
        }
    }
}

// Make podInstall depend on syncIosVersion to ensure version is synced before building
tasks.matching { it.name == "podInstall" }.configureEach {
    dependsOn("syncIosVersion")
}

// -------------------- Helper Functions --------------------
fun getArtifactName(defaultConfig: com.android.build.gradle.internal.dsl.DefaultConfig): String = "${appName.replace(" ", "")}-${defaultConfig.versionName}_${defaultConfig.versionCode}"

// -------------------- Swift Bridge Configuration --------------------
// Ensure Swift bridge objects are built before linking iOS frameworks. SDK-specific aggregates
// so a simulator link doesn't also compile device bridge objects (and vice versa);
// `compileSwiftBridge` stays available as the both-SDKs convenience umbrella.
tasks
    .matching { it.name.startsWith("link") && it.name.contains("IosSimulatorArm64") && !it.name.contains("Test") }
    .configureEach {
        dependsOn(":shared:domain:compileSwiftBridgeIphonesimulator")
        dependsOn(":shared:presentation:compileSwiftBridgeIphonesimulator")
    }
tasks
    .matching { it.name.startsWith("link") && it.name.contains("IosArm64") && !it.name.contains("Test") }
    .configureEach {
        dependsOn(":shared:domain:compileSwiftBridgeIphoneos")
        dependsOn(":shared:presentation:compileSwiftBridgeIphoneos")
    }
